### ISSUE TITLE
Review Mar 11 (on mobile)

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji.org#160]
Menu:
- "X" seems duplicated, to be a small X inside a big X
![IMG_479F7FA8E923-1](https://user-images.githubusercontent.com/480224/157884088-3a5ca3a4-8c17-4aa6-ad20-3dc4defdb2c4.jpeg)

Home:
- Missing padding for "Or try OpenMoji on your phone"
- First big button looks slightly broken  
![IMG_5AC12520BBF1-1](https://user-images.githubusercontent.com/480224/157883223-149d589d-bcf1-4e05-97d8-fff1f1caa5b9.jpeg)

Emoji detail view:
- Red "X" to close view is quite small on mobile, would be better to increase size

Library (only Firefox):
- Can't click the emojis in the list to go to the detail view
- Firefox app becomes unresponsive after a wile or on reloading 
- List ends abruptly and doesn't show remaining emojis 
![IMG_BF9A39F752FB-1](https://user-images.githubusercontent.com/480224/157882872-d0d88ef8-7a06-4fcd-8c3d-4d773dc24054.jpeg)

About:
- It would be an honour to have **you** listed there as well! :)

**Comment by stephanbogner** [comment]
@b-g

**(1) Regarding "First big button looks slightly broken": How should it ideally look like?**
(Because it's always an issue with fully rounded buttons, that they look weird once a line break happens. Technically it does behave correctly as "Contribute" is too wide to fit into the remaining space and thus breaks into the next line.)

**(2) Otherwise all issues should (🤞) be fixed**

**(3) We now finally even have working pages for all emojis 🎉** (Example for a standard [yellow emoji](https://lab.stephanbogner.de/library/emoji-1F600), one with [skintones](https://lab.stephanbogner.de/library/emoji-1F44C#variant=1F44C-1F3FD) and one with [multi-skintones](https://lab.stephanbogner.de/library/emoji-1F469-200D-2764-FE0F-200D-1F48B-200D-1F468/#variant=1F469-1F3FB-200D-2764-FE0F-200D-1F48B-200D-1F468-1F3FF))

↓

**So it would be great if you could do another review session on [lab.stephanbogner.de](https://lab.stephanbogner.de/) 🙏**

**Comment by b-g** [comment]
Hi @stephanbogner, MEGA! The new views look super lovely!! All great + super that it runs smoothly on Firefox mobiles as well!

1. looks now good (enough)
2. 👍 
3. 👍 

I found these broken links (don't point to the generate detail sites):
![2022-04-29 at 08 28](https://user-images.githubusercontent.com/480224/165895238-8cb419c1-b51a-4747-9d67-a4aa6505333d.jpg)


Could you afterwards: 
- deploy 
- write a few tweets 
- let the Astro peeps know about it
- close this issue :)

**Comment by b-g** [comment]
afterwards: close this issue and the addressed ones eg. #164
