### ISSUE TITLE
About: Please align OpenMojis in about text to baseline

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji.org#162]
Could you please y translate all openmojis so that they fit nicely together with the about text?

![Screen Shot 2022-03-15 at 08 52 00](https://user-images.githubusercontent.com/480224/158331561-010bde0b-90bc-47c1-8d87-615cd632ad1f.jpg)

**Comment by stephanbogner** [comment]
You are using Firefox, I assume?

I am gonna have a look, why it doesn't look like in Chrome:
<img width="625" alt="Screenshot 2022-03-15 at 12 56 27" src="https://user-images.githubusercontent.com/7897006/158372832-be543d6b-454b-4e85-aa26-f739030a9e2e.png">

**But in any case:**
Which Emoji should I base the translation on?
(I used the cat for reference, but now seeing it again it doesn't work well with the normal smileys.)

**Comment by b-g** [comment]
Ups ... again this Firefox. Sorry!

I would go with any which is aligned like this e.g. 1F3F7.svg
![2022-03-15 at 13 58](https://user-images.githubusercontent.com/480224/158382904-04366686-c7b3-4d97-a722-6882e6a6dca2.jpg)

**Comment by stephanbogner** [comment]
### The joys of cross-browser font-rendering 😅 ☠️ 

**(Currently) On the left Chrome and on the right Firefox:**
You can see that the line heights are completely different

<img width="1280" alt="Screenshot 2022-04-26 at 10 40 30" src="https://user-images.githubusercontent.com/7897006/165260928-9d12f0b6-b212-4bcf-8ac7-1e3634fb1574.png">

**(New approach) On the left Chrome and on the right Firefox:**
I now changed the approach: I now artificially make the height of the emoji container small and center align using flexbox. That might be even nicer because it doesn't affect the line height, as it normally does with Emoji.

<img width="1280" alt="Screenshot 2022-04-26 at 10 45 20" src="https://user-images.githubusercontent.com/7897006/165261170-3d3b8779-c1b0-4f74-84cc-a2b36be7a57b.png">

**Comment by dnlutz** [comment]
the details … thank you!
