### ISSUE TITLE
About: Stephan Bogner and Astro links are not click able

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji.org#170]
Reported via Email by @birbilis, thanks! cc @stephanbogner 

> 
> https://openmoji.org/about/#contact
> the last credit has links that aren’t clickable (on Bogner and on Astro)
> (there’s probably some issue with the page markup)

**Comment by stephanbogner** [comment]
Ok, really weird:

- It's only broken when using the hash link: https://openmoji.org/about/#contact
- It works fine when you go to https://openmoji.org/about/ and scroll down manually

The culprit is that bit in [global.scss](https://github.com/hfg-gmuend/openmoji.org/blob/master/src/shared-styles/global.scss#L68):
````
:target:before {
    content: "";
    display: block;
    position: relative;
    height: 80px;
    margin-top: -80px;
}
````

@b-g Do you know the purpose of this? Otherwise I'd just remove it and see if it breaks something somewhere.

**Comment by b-g** [comment]
Hi @stephanbogner, many thanks for investigating! No idea ... please remove and test :)

**Comment by stephanbogner** [comment]
Ok, the CSS is quite smart actually. 

I artificially pushes the content down, so that nothing is hidden behind the sticky header.
I added it's purpose as a comment and added `pointer-events: none;` as a fix.

**Comment by b-g** [comment]
@birbilis Many thanks for reporting! But this is totally the wrong place to discuss :) Please:
- repost under the main OpenMoji repo
- be more verbose and provide images
THX
